import type { GenericTemplateModule } from "./types";

/**
 * Standard Terms body for an AI Addendum, adapted from
 * templates/AI-Addendum.md. This addendum supplements a base Agreement and
 * has no Effective Date, Governing Law, or Chosen Courts of its own; all
 * deal-specific Variables (Training Data, Training Purposes, Training/
 * Improvement Restrictions...) are left as bracketed placeholders instead
 * of being asked as fields.
 *
 * Source: https://commonpaper.com/standards/ai-addendum/1.0/ (CC BY 4.0)
 */
const STANDARD_TERMS_TEMPLATE = `1. **AI Services**
    1. **Using AI Services.** The AI Services are part of the Product and subject to the Agreement as supplemented by this AI Addendum. Customer may use AI Services by providing Input, and the AI Services may generate Output in response. Provider may copy, display, modify, distribute, and use Input to the extent necessary to provide the AI Services, and Customer authorizes Provider to process Input for those purposes.
    2. **Restrictions.** Without limiting the restrictions in the Agreement, Customer will not (and will not allow anyone else to): (a) use the AI Services for decision-making in a regulated industry without proper human oversight in compliance with Applicable Laws and professional ethics; (b) use the AI Services to infringe the intellectual property or other rights of others; or (c) falsely state Output was created by a human.
    3. **Model Training.** Unless the Cover Page identifies [Training Data] and [Training Purposes], Provider may not use Customer's Inputs or Outputs to Train any Model. If the Cover Page permits Training, Provider may copy, modify, distribute, and use [Training Data] for the [Training Purposes], subject to the [Training Restrictions].
    4. **Non-Training Improvement.** Subject to the [Improvement Restrictions], Provider may use Input, Output, and [Training Data] to provide, maintain, develop, and improve the AI System, provided that such use does not constitute Training except as authorized for the [Training Purposes].
2. **Intellectual Property and Privacy**
    1. **Ownership.** As between the parties, Customer retains all right, title, and interest in Input and owns all Output; Provider assigns to Customer, to the extent permitted by Applicable Laws, any right, title, and interest it may have in Output.
    2. **Personal Data.** Nothing in this AI Addendum reduces or limits Provider's obligations under Applicable Data Protection Laws regarding Personal Data that may be contained in Input.
    3. **Rights to Input.** Customer represents and warrants that it, all Users, and anyone submitting Input have and will continue to have all rights necessary to submit Input to the AI Services.
3. **Disclaimers**
    1. **Nature of AI.** Due to the nature of artificial intelligence and machine learning, information generated by the AI Services may be incorrect or inaccurate. The AI Services are not human and are not a substitute for human oversight. Output may not be protectable as intellectual property.
    2. **Similarity of Output.** Output may resemble or duplicate data, information, or materials the AI Services created for others. Provider does not represent or warrant that Output will not incorporate others' data, infringe third-party rights, or be reproduced similarly for another user.
4. **Definitions**
    1. **"AI Services"** means the artificial intelligence or machine learning components of the Product, including the AI System and underlying Model(s).
    2. **"AI System"** means the artificial intelligence or machine learning application, program, and services layers of the AI Services, excluding the underlying Models.
    3. **"Input"** means the data, information, prompts, or materials submitted by or on behalf of Customer or Users to the AI Services, excluding Feedback.
    4. **"Model"** means a large language, machine learning, or artificial intelligence model.
    5. **"Output"** means the data, information, or materials created by the AI Services in response to Input.
    6. **"Train"** or **"Training"** means the use of data, information, or materials to create or improve a Model.

Adapted from the Common Paper AI Addendum [Standard Terms Version 1.0](https://commonpaper.com/standards/ai-addendum/1.0/), free to use under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).
`;

export const aiAddendum: GenericTemplateModule = { STANDARD_TERMS_TEMPLATE };
